language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

before_script:

script:
  ./gradlew build
  
after_success:
  - ./gradlew jacocoTestReport coveralls crashlyticsUploadDistributionDebug
