language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

script:
  ./gradlew build